import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useRouter } from "next/navigation";
import NavButton from "../components/navbutton";
import NavMenu from "../components/navmenu";
// import NavBar from './_NavBar/page';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const goPageHandler = (e, value) => {
    e.preventDefault();
    useRouter.push(value);
  };

  return (
    <div className="w-[1366px] m-auto bg-slate-600">
      <head>
        <title className="test">My tl site</title>
      </head>
      <header>
        <h1>My t1 site</h1>
      </header>
      <NavMenu>
        <NavButton pageInfo={{ name: "홈", endPoint: "/" }}></NavButton>
        <NavButton
          pageInfo={{ name: "Button1", endPoint: "/button1" }}
        ></NavButton>
        <NavButton
          pageInfo={{ name: "Button2", endPoint: "/button2" }}
        ></NavButton>
        <NavButton
          pageInfo={{ name: "Button3", endPoint: "/button3" }}
        ></NavButton>
      </NavMenu>
      {children}
      <footer>
        <div>footer</div>
      </footer>
    </div>
  );
}
